### PR TITLE
Update the ReadME.md

### PR DESCRIPTION
**Pull request by kdaglas**
I have updated my ReadME.md to give a brief description of what my app does.

### CODE REVIEW

**Review by 66hakeem — COMMENTED** [review]
Nice ReadMe you've got.

**Review by kaggwachristopher — APPROVED** [review]
wow,looks more professional than the first one...good to merge

**Comment by joelethan** [comment]
Nice ReadMe file, and very descriptive as well. Good job

**Comment by jeanjoe** [comment]
Well organized work

**Pull request merged**
